# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ab7462226cb7299917bfb7f9906ca5c8b37f3e4a5b0bf39d8bb67e361bb660ae297c0fa6ba2bcb9775db38cb5658e274ddfe739c4e63cf8dd9e7d1b32db0b36

test:
  secret_key_base: 39827826a2e5c2514e6ee0ab862a9812ffae8ea3c76db969e98fc04d5cbebf3024f74d19ce8f741bf5d3eca964e8458227b0100b2fd317564ff082d330effb96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
